# Generated by Django 3.2.4 on 2021-08-16 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210816_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='post-images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'gif', 'jpeg'])]),
        ),
    ]
