# Generated by Django 3.2.4 on 2021-08-28 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='ffriends', to=settings.AUTH_USER_MODEL),
        ),
    ]
