# Generated by Django 3.2.4 on 2021-09-06 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friendship', '0006_auto_20210828_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('friend_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='friendship.friend')),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=('friendship.friend',),
        ),
    ]
