# Generated by Django 3.2.4 on 2021-08-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followee',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
