# Generated by Django 3.2.4 on 2021-09-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friendship', '0004_auto_20200408_1844'),
        ('friends', '0003_auto_20210828_1044'),
    ]

    def sync_friendship(app, schema_editor):
        from django.apps import apps
        Friend = apps.get_model("friends", "Friend")
        Friend_Ptr = apps.get_model("friendship", "Friend")
        friend_ptrs = Friend_Ptr.objects.all()
        for friend_ptr in friend_ptrs:
            if not hasattr(friend_ptr, "friend"):
                Friend.objects.create(friend_ptr=friend_ptr, is_active=True)

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('friend_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='friendship.friend')),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=('friendship.friend',),
        ),
        migrations.RunPython(sync_friendship,),
    ]
