# Generated by Django 3.2.4 on 2021-07-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ManyToManyField(blank=True, related_name='group_admin', to='profiles.Profile'),
        ),
    ]
