# Generated by Django 3.2.3 on 2021-06-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='updated',
        ),
    ]
