# Generated by Django 3.2.4 on 2022-01-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='BanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_status', models.BooleanField(default=False)),
                ('ban_date', models.DateTimeField(auto_now=True)),
                ('group_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
        ),
    ]
