# Generated by Django 3.2.4 on 2021-08-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('groups', '0004_auto_20210801_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admin',
        ),
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ManyToManyField(blank=True, related_name='group_admin', to='profiles.Profile'),
        ),
    ]
